tests:
  build: .
  dockerfile: testDockerfile
  volumes:
    - ".:/go/src/github.com/sidewinder-team/sidewinder-server"
  links:
    - "testmongo:mongo"
testmongo:
  extends:
    file: docker-compose.yml
    service: mongo
  log_driver: none
