tests:
  build: .
  dockerfile: testDockerfile
  volumes:
    - .:/go/src/github.com/sidewinder-team/sidewinder-server
  ports:
    - "8000:8000"
  links:
    - "mongo:mongo"
mongo:
  image: tutum/mongodb
  environment:
    - AUTH=no
